run:
  timeout: 5m
  skip-dirs:
    - frontend
    - node_modules

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofumpt
    - gomnd
    - nlreturn
    - testpackage
    - wsl
    - stylecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - goconst
        - maintidx
