services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  board-service:
    build: ./board-service
    ports:
      - "8081:8080"
    env_file:
      - ./board-service/.env
    networks:
      - kafka-net
    depends_on:
      mongo-board:
        condition: service_started
      kafka: 
        condition: service_healthy

  task-service:
    build: ./task-service
    ports:
      - "8082:8080"
    env_file:
      - ./task-service/.env
    depends_on:
      mongo-task:
        condition: service_started
      kafka: 
        condition: service_healthy
    networks:
      - kafka-net

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/.env
    networks:
      - kafka-net
    depends_on:
      mongo-user:
        condition: service_started
      kafka: 
        condition: service_healthy

  notification-service:
    build: ./notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "8083:8080"
    networks:
      - kafka-net
    depends_on:
      user-service:
        condition: service_started
      mongo-notification:
        condition: service_started
      kafka: 
        condition: service_healthy

  mongo-board:
    image: mongo
    container_name: mongo-board
    ports:
      - "27018:27017"
    volumes:
      - mongo_board_data:/data/db
    networks:
      - kafka-net
    command: mongod --quiet --logpath /dev/null

  mongo-task:
    image: mongo
    container_name: mongo-task
    ports:
      - "27019:27017"
    volumes:
      - mongo_task_data:/data/db
    networks:
      - kafka-net
    command: mongod --quiet --logpath /dev/null

  mongo-user:
    image: mongo
    container_name: mongo-user
    ports:
      - "27020:27017"
    volumes:
      - mongo_user_data:/data/db
    networks:
      - kafka-net
    command: mongod --quiet --logpath /dev/null

  mongo-notification:
    image: mongo
    container_name: mongo-notification
    ports:
      - "27021:27017"
    volumes:
      - mongo_notification_data:/data/db
    networks:
      - kafka-net
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo_board_data:
  mongo_task_data:
  mongo_user_data:
  mongo_notification_data:

networks:
  kafka-net:
    driver: bridge