global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["user-service:8080"]

  - job_name: "board-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["board-service:8080"]

  - job_name: "task-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["task-service:8080"]

  - job_name: "notification-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notification-service:8080"]

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]